/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefTestRouteImport } from './routes/ref-test'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as IndexRouteImport } from './routes/index'

const RefTestRoute = RefTestRouteImport.update({
  id: '/ref-test',
  path: '/ref-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prototype': typeof PrototypeRoute
  '/ref-test': typeof RefTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prototype': typeof PrototypeRoute
  '/ref-test': typeof RefTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prototype': typeof PrototypeRoute
  '/ref-test': typeof RefTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prototype' | '/ref-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prototype' | '/ref-test'
  id: '__root__' | '/' | '/prototype' | '/ref-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrototypeRoute: typeof PrototypeRoute
  RefTestRoute: typeof RefTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ref-test': {
      id: '/ref-test'
      path: '/ref-test'
      fullPath: '/ref-test'
      preLoaderRoute: typeof RefTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrototypeRoute: PrototypeRoute,
  RefTestRoute: RefTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
